import asyncio
import base64
import logging
import pathlib
import time
from dataclasses import dataclass

import httpx

from app.github.app_auth import get_installation_token
from app.models.review import RepoContext

logger = logging.getLogger(__name__)

GITHUB_API = "https://api.github.com"

# Per-file character cap to prevent context overflow
MAX_CHARS_PER_FILE = 4000
# Combined cap across all context files
MAX_TOTAL_CHARS = 12000
# Cache TTL — context files change rarely, but refresh every 30 min
_CONTEXT_TTL_SECS = 1800

# Local context directory — generated by scripts/generate_context.py
# Layout: mreview-context/{owner}/{repo}/  (e.g. mreview-context/Meesho/store-front/)
_LOCAL_CONTEXT_ROOT = pathlib.Path("mreview-context")

_MREVIEW_FILES = [
    ("incidents",        "incidents.md"),
    ("review_learnings", "review-learnings.md"),
    ("architecture",     "architecture.md"),
    ("anti_patterns",    "anti-patterns.md"),
]


@dataclass
class _CachedRepoContext:
    context: RepoContext
    fetched_at: float


_context_cache: dict[str, _CachedRepoContext] = {}


async def _fetch_one(
    client: httpx.AsyncClient,
    repo: str,
    filename: str,
    headers: dict,
) -> str | None:
    """
    Fetch .mreview/{filename} from the repo root.
    Returns None on 404 or error. Truncates at MAX_CHARS_PER_FILE.
    """
    try:
        resp = await client.get(
            f"{GITHUB_API}/repos/{repo}/contents/.mreview/{filename}",
            headers=headers,
        )
        if resp.status_code == 404:
            logger.debug(".mreview/%s not found in %s", filename, repo)
            return None
        resp.raise_for_status()
        content = base64.b64decode(resp.json()["content"]).decode("utf-8")
        if len(content) > MAX_CHARS_PER_FILE:
            content = content[:MAX_CHARS_PER_FILE].rsplit("\n", 1)[0]
            content += "\n[truncated — file exceeds per-file context budget]"
            logger.info(".mreview/%s in %s truncated to %d chars", filename, repo, MAX_CHARS_PER_FILE)
        return content
    except Exception as exc:
        logger.warning("Failed to fetch .mreview/%s for %s: %s", filename, repo, exc)
        return None


def _load_local_context(repo: str) -> RepoContext | None:
    """
    Try to load .mreview/ files from the local mreview-context/ directory.
    Returns None if no local directory exists for this repo.
    Layout: mreview-context/{owner}/{repo}/  (e.g. mreview-context/Meesho/store-front/)
    """
    # repo is "owner/name" — map to mreview-context/name/
    repo_name = repo.split("/", 1)[-1]
    local_dir = _LOCAL_CONTEXT_ROOT / repo_name
    if not local_dir.is_dir():
        return None

    kwargs: dict[str, str | None] = {}
    for field_name, filename in _MREVIEW_FILES:
        path = local_dir / filename
        if not path.exists():
            kwargs[field_name] = None
            continue
        content = path.read_text(encoding="utf-8")
        if len(content) > MAX_CHARS_PER_FILE:
            content = content[:MAX_CHARS_PER_FILE].rsplit("\n", 1)[0]
            content += "\n[truncated]"
        kwargs[field_name] = content

    context = RepoContext(**kwargs)
    logger.info(
        "Loaded local .mreview/ context for %s — found: %s",
        repo, context.present_files() or ["none"],
    )
    return context


async def fetch_repo_context(repo: str) -> RepoContext:
    """
    Load .mreview/ context files for the given repo.

    Priority:
      1. Local files in mreview-context/{repo}/ (generated by scripts/generate_context.py)
      2. GitHub Contents API (falls back when no local files exist)

    Results are cached per-repo with a 30-minute TTL.
    """
    cached = _context_cache.get(repo)
    if cached and (time.time() - cached.fetched_at) < _CONTEXT_TTL_SECS:
        logger.debug("Using cached .mreview/ context for %s", repo)
        return cached.context

    # Try local files first
    local_context = _load_local_context(repo)
    if local_context is not None:
        _context_cache[repo] = _CachedRepoContext(context=local_context, fetched_at=time.time())
        return local_context

    # Fall back to GitHub API
    logger.debug("No local context for %s — fetching from GitHub", repo)
    token = await get_installation_token(repo)
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    async with httpx.AsyncClient() as client:
        results = await asyncio.gather(
            *[_fetch_one(client, repo, filename, headers) for _, filename in _MREVIEW_FILES],
            return_exceptions=True,
        )

    kwargs: dict[str, str | None] = {}
    for (field_name, filename), result in zip(_MREVIEW_FILES, results):
        if isinstance(result, Exception):
            logger.warning("Exception fetching .mreview/%s: %s", filename, result)
            kwargs[field_name] = None
        else:
            kwargs[field_name] = result

    context = RepoContext(**kwargs)
    _context_cache[repo] = _CachedRepoContext(context=context, fetched_at=time.time())
    logger.info(
        "Fetched .mreview/ context for %s from GitHub — found: %s",
        repo, context.present_files() or ["none"],
    )
    return context
